### ISSUE TITLE
OOV tokens

### ISSUE THREAD

**Issue by bdhingra** [PrincetonML/SIF#5]
Hi,

Thanks for sharing the code! I have some questions about the handling of OOV tokens:

1. How is the sentence embedding computed if any of its words does not have a pretrained vector in GloVe?
2. Say we encounter a word at test time which was not present in the corpus used for estimating word frequencies. How is the weight for this word computed?
3. Do you remove infrequent words when computing the word frequencies from the corpus? I ask because the vocab file name (enwiki_vocab_min200.txt) seems to suggest so. If yes, how are the removed tokens weighted?

Thanks in advance for your time :)

Best,
Bhuwan

**Comment by YingyuLiang** [comment]
For 1 and 2, I simply ignored such out-of-vocabulary words.

For 3, yes, I ignored words appearing less than 200 times in Wikipedia.  This seems to be a bit contradictory to my way to deal with 1 and 2: if those infrequent words were taken into account, then they would get weight close to 1, but now they get ignored (ie, weight 0). This didn't cause a problem for my experiments, since such words occur very rarely. I've also tested using say a larger or smaller vocabulary, which only changed the performance very slightly (~0.3%).

But if you have words modestly frequent in the test corpus but very infrequent in the corpus for computing the word frequency, then you should make effort to get a better estimate of the frequency of the words. Similarly, if you don't get a pretrained vector for a modestly frequent word in the test corpus, then it may cause some problem.

**Comment by bdhingra** [comment]
Thanks a lot for the prompt response!

**Comment by bdhingra** [comment]
Sorry to reopen the issue, but regarding 1 and 2 it seems that these words are not simply ignored:

1. Based on the code [here](https://github.com/YingyuLiang/SIF/blob/master/src/data_io.py#L36) it seems that if the word is not in GloVe, either the embedding for `UUUNKKK` is used, or the "last" embedding in the file is used.
2. Based on the code [here](https://github.com/YingyuLiang/SIF/blob/master/src/data_io.py#L295) it seems that if a word does not have an associated frequency then it is assigned a weight of 1.

Can you please confirm if my understanding is correct? If so where does the embedding for `UUUNKKK` come from?

Thanks,
Bhuwan

**Comment by YingyuLiang** [comment]
Oh yes, you're right. The code here used part of the code from John Wieting's, where UUUNKKK is used as a "default" word. Its vector is pre-trained; you can also pick some other default word with pre-trained vector.

I had also done experiments using some other design choice but it didn't seem to affect the performance much as long as I can remember. That's what my previous reply described. But since the code here used the  default word vector and weight 1 for words without precomputed frequency, you can follow these choices if you want to use the code.
